Slice admin template
VratsaSoftware/PriceDropWatcher pull request #6
Opened 2021-05-23 19:54 UTC by stani1940

2021-06-17 06:48 UTC, cvexa requested changes

2021-06-17 06:48 UTC, cvexa commented on app/Http/Controllers/Auth/RegisterController.php
> +            'role_id' => 2,
по-добре ще е ако ид-то на ролята се взима със заявка, вместо да е хард-кодната, тоест, първо взимаш от ролите която е потребител, и тогава и слагаш ид-то

2021-06-17 06:48 UTC, cvexa commented on app/Http/Requests/ProfileCreateUpdateRequest.php
> +            'image.required'  => 'Choose picture!',
може би е добре да се добави валидация, за типа на файла и размер, за да не се опитва някой примерно да качи текстов документ, или много голям файл, който да забие програмата ни

2021-06-17 06:48 UTC, cvexa commented on app/Http/Controllers/ProfileController.php
> +            ->storeAs('public/images', $request->user()->name .'.' . $ext);
за да се избегне евентуално, 2 потребителя с еднакво име, да качат с еднакво име файлове, най-добре е да се добави към името на файла който записваш и текущото време например, така шанс се свежда до нулев (може и като милисекунди)

2021-06-17 06:48 UTC, cvexa commented on routes/web.php
> +Route::get('/profile/{user}/edit','ProfileController@edit')->name('edit_profile');
защо не използваме ресурсните пътища [()](https://laravel.com/docs/8.x/controllers#actions-handled-by-resource-controller)

2021-06-21 19:17 UTC, stani1940 commented on routes/web.php
> +Route::get('/profile/{user}/edit','ProfileController@edit')->name('edit_profile');
имаме само редакция на профила и за това ги дадох двата с get и put имената аз си ги измислих

2021-07-28 07:09 UTC, merged